### ISSUE TITLE
prom scraper exits immediately if no positive scrape intervals

### ISSUE THREAD

**Issue by MirahImage** [cloudfoundry/loggregator-agent-release#233]
In the case that all prom scraper configurations have negative scrape intervals, prom scraper exits immediately as nothing is added to the wait group. This immediate exit causes monit to consider the process failed, restarting it, and eventually causing bosh to consider the instance/deployment failing.

**Comment by ctlong** [comment]
Instead of adding code to fix this case, it might be preferable to simply remove the prom_scraper job from a VM that has no prom scraper configurations, or all prom scraper configurations have a negative interval. I guess that's harder to reason about at deployment time though 🤔 .

❓ Is there a way to stop a process that monit considers as a success that it doesn't need to restart?

**Comment by Benjamintf1** [comment]
Forwarder agent, syslog-agent, loggregator-agent I think all have prom scraper config. How is this possible?

**Comment by chombium** [comment]
@MirahImage This looks very intriguing. How and when does this happen, what do you want to achieve and what is your setup? From what you've described so far it looks to me that you are not using the cf-deployment or if you are, you're doing some extra changes, so that the prom_scraper doesn't get properly configured. 

IMO: If the there is no proper configuration it's normal for the prom_scraper to fail and one should check what's wrong. If one doesn't have a valid use case for the scraper, one should not deploy it.

@Benjamintf1 I'm wondering that too...

@ctlong If the process is stopped expicitly with `monit stop`, monit won't try to restart it. I'm not sure if we should go that far, though. Even if we make sure that in our `loggtegator-agent-release` everything is configured properly, one can still use the prom_scraper separately, outside cfd or configure it wrongly. For me no config or negative scrape intervals in all configs is an error state and the prom_scraper should log wrong config message and exit. The other option would be wait indefinitely until it gets a proper config which IMO is completely wrong. Why would someone use a program which is not configured properly?

**Comment by MirahImage** [comment]
This is in the RabbitMQ tile, with on-demand RabbitMQ instances, not in cf itself, and the scrape interval is user configurable. In some instances, users wish to disable the scrape action, and do so by configuring a negative scrape interval, as documented. In this case, because no go-routines were created, the wait group is empty, resulting in an immediate exit.

This is in many ways a continuation of an earlier issue where negative scrape intervals resulted in prom scraper crashing. Prior to https://github.com/cloudfoundry/loggregator-agent-release/pull/174 prom scraper would crash when a negative scrape interval was configured. However, now it simply exits. 

Regarding BOSH jobs, they are expected to run forever. Any job that exits is considered to be failed and will be restarted by monit, the exception being errands.

**Comment by MirahImage** [comment]
I've realized that there's an extra source of confusion, as there two places where the scrape interval is configurable: both in the `prom_scraper_config.yml` and the `scrape_interval` in the job spec.

**Comment by Benjamintf1** [comment]
Are you setting the job spec scrape interval to <0? You should not do that. 

If that's not the case, how is all the prom_scraper_config.yml's negative if forwarder agent is necessary to be there to function, and uses prom scraper?

**Comment by MirahImage** [comment]
Indeed, that appears to be what was done, and had been working. We're now correcting this. We appear to have solved our problem without requiring further prom_scraper changes.

**Comment by Benjamintf1** [comment]
Cool, sounds like this is resolved?
