### ISSUE TITLE
Syslog-agent does not sanitize hostame

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/loggregator-agent-release#31]
The syslog hostname has historically been sanitized to comply with RFC 1034. https://github.com/cloudfoundry/cloud_controller_ng/blob/a732bdfe9c8013e69fd610f342b00c0ce384b1c8/spec/unit/controllers/internal/syslog_drain_urls_controller_spec.rb

The syslog agents don't do this when the org, space, and app names exist as tags on the logs:
https://github.com/cloudfoundry/loggregator-agent-release/blob/4125b9897614b6e711591a635ce09c7c46b2686c/src/pkg/egress/syslog/rfc5424.go#L66-L81

This might allow invalid characters into the hostname and break downstream log consumers

**Comment by katter** [comment]
Just wanted to give a heads up and mention that we're affected by this and are losing logs from several spaces.

**Comment by jriguera** [comment]
We are having issues because of this change. Some users created spaces or apps with `_`, so the resulting hostname field is something like `my_app.my_space.organization`, and as you know `_` is not an allowed character data in DNS names. 
Also, I think is is a breaking change and I could not find it in the release notes.

**Comment by andrew-edgar** [comment]
As you might be able to tell from above.  I have submitted a PR to help solve this in the syslog agents.

**Comment by pianohacker** [comment]
This has been fixed, and will be released in 6.0.2 in the next few days.
