### ISSUE TITLE
Hostnames in app syslog drains should update after a rename

### ISSUE THREAD

**Issue by pianohacker** [cloudfoundry/loggregator-agent-release#33]
Note: it does not seem possible to fix this for aggregate syslog drains.

**Comment by johnnyTest20** [comment]
Is there any update to this issue? We are having the same issue where the source name is not updating after blue-green deployment

**Comment by pianohacker** [comment]
We are in conversations with the diego team about this issue. No timeline on a fix as of yet.

**Comment by ctlong** [comment]
I think that the recent feature to rename app logs and metrics after renames should have resolved this issue. Please re-open if that's not the case :).

**Comment by pianohacker** [comment]
Holy cow, did y'all actually fix this bug? How? This was an incredibly tangled problem, I'm very curious.

**Comment by ctlong** [comment]
It was a very complex problem!

We toyed with a few different options before ultimately deciding to [add metric tags to DesiredLRP updates](https://github.com/cloudfoundry/diego-release/issues/662). There was some prior art for taking DesiredLRP updates and applying the changes directly to any ActualLRPs that we were able to crib from.

So whenever an app is renamed:
* CAPI now sends an immediate DesiredLRP update to BBS with the new metric tags
  * If the request to BBS fails, the bulk sync loop between BBS and CAPI will send a DesiredLRP update
* BBS updates any associated ActualLRPs with the new metric tags and pushes the updates to the reps involved
  * If any of those updates fail, they'll be resolved in the sync loop between that rep and BBS
* The reps acknowledge the ActualLRP changes and update the metric tags on the source associated with the app, so that any logs or metrics for that app will use the new metric tags
* A new, separate component on each Diego Cell, silk-datastore-syncer, starts a sync loop where it requests all the ActualLRPs on the node from BBS and updates the networking metadata on disk with any new metric tags
